version: '3'
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROMETHEUS_VERSION: ${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"
    restart: unless-stopped
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: unless-stopped
    container_name: grafana